### ISSUE TITLE
Multiple versions warning spam messages

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#309]
Projects  importing @acala-network/test-providers are finding a lot of errors along the lines of @polkadot/util has multiple versions, ensure that there is only one installed.

It this fixable at this package level?

**Comment by shunjizhan** [comment]
at the package level we already locked all versions https://github.com/AcalaNetwork/bodhi.js/blob/master/common/config/rush/.pnpmfile.cjs#L21

Is it because the other project explicitly installed some other versions of the overlapping packages? They can try use the same versions as we do, or add version locks in their package json

**Comment by shunjizhan** [comment]
@ThunderDeliverer by the way I remember seeing similar warning when installing packages with `yarn` for the tutorials, maybe we should also lock the versions in tutorials to make them consistent with bodhi?

**Comment by gluneau** [comment]
Fixed by https://github.com/AcalaNetwork/bodhi.js/pull/380
